# Generated by Django 2.2.7 on 2019-11-07 22:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('AdministrativeOfficer', '0001_initial'),
        ('parent', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Course',
            fields=[
                ('courseID', models.AutoField(primary_key=True, serialize=False)),
                ('courseName', models.CharField(max_length=50)),
                ('year', models.CharField(max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='Teacher',
            fields=[
                ('teacher_id', models.AutoField(primary_key=True, serialize=False)),
                ('fiscalCode', models.CharField(max_length=20)),
                ('name', models.CharField(max_length=100)),
                ('surname', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254)),
                ('password', models.CharField(max_length=100)),
                ('coordinatedClass', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='AdministrativeOfficer.ClassInfo')),
                ('coursesTaught', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='teacher.Course')),
            ],
        ),
        migrations.CreateModel(
            name='Note',
            fields=[
                ('noteID', models.AutoField(primary_key=True, serialize=False)),
                ('noteText', models.CharField(max_length=300)),
                ('courseID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='teacher.Course')),
                ('studentID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='parent.Student')),
            ],
        ),
        migrations.CreateModel(
            name='FreeSlots',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('schedule', models.CharField(max_length=24)),
                ('teacher', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='teacher.Teacher')),
            ],
        ),
        migrations.CreateModel(
            name='Content',
            fields=[
                ('contentID', models.AutoField(primary_key=True, serialize=False)),
                ('contentString', models.CharField(max_length=100)),
                ('courseID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='teacher.Course')),
            ],
        ),
        migrations.CreateModel(
            name='Attendance',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('presence', models.BooleanField(default=True)),
                ('date', models.DateField()),
                ('came_late', models.BooleanField(default=False)),
                ('left_early', models.BooleanField(default=False)),
                ('course_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='teacher.Course')),
                ('student_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='parent.Student')),
            ],
        ),
    ]
