# Generated by Django 2.2.7 on 2019-11-07 22:04

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='FinalGrade',
            fields=[
                ('gradeID', models.AutoField(primary_key=True, serialize=False)),
                ('finalGrade', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Parent',
            fields=[
                ('parentID', models.AutoField(primary_key=True, serialize=False)),
                ('fatherName', models.CharField(max_length=50)),
                ('fatherEmail', models.EmailField(max_length=254)),
                ('motherName', models.EmailField(max_length=254)),
                ('fatherPassword', models.CharField(max_length=100)),
                ('motherPassword', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='performanceGrade',
            fields=[
                ('gradeID', models.AutoField(primary_key=True, serialize=False)),
                ('date', models.DateField()),
                ('grade', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Student',
            fields=[
                ('studentID', models.AutoField(primary_key=True, serialize=False)),
                ('studentName', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='StudentCourse',
            fields=[
                ('ID', models.AutoField(primary_key=True, serialize=False)),
            ],
        ),
    ]
