# Generated by Django 2.2.7 on 2019-11-07 22:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('parent', '0001_initial'),
        ('AdministrativeOfficer', '0001_initial'),
        ('teacher', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='studentcourse',
            name='courseID',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='teacher.Course'),
        ),
        migrations.AddField(
            model_name='studentcourse',
            name='studentID',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='parent.Student'),
        ),
        migrations.AddField(
            model_name='student',
            name='classID',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='AdministrativeOfficer.ClassInfo'),
        ),
        migrations.AddField(
            model_name='performancegrade',
            name='courseID',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='teacher.Course'),
        ),
        migrations.AddField(
            model_name='performancegrade',
            name='studentID',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='parent.Student'),
        ),
        migrations.AddField(
            model_name='parent',
            name='studentID',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='parent.Student'),
        ),
        migrations.AddField(
            model_name='finalgrade',
            name='courseID',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='teacher.Course'),
        ),
        migrations.AddField(
            model_name='finalgrade',
            name='studentID',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='parent.Student'),
        ),
        migrations.AlterUniqueTogether(
            name='performancegrade',
            unique_together={('studentID', 'courseID', 'date')},
        ),
    ]
