# Generated by Django 2.2.7 on 2019-11-07 22:03

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AdministrativeOfficer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254)),
                ('password', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Announcements',
            fields=[
                ('announcement_id', models.AutoField(primary_key=True, serialize=False)),
                ('announcementText', models.CharField(max_length=500)),
            ],
        ),
        migrations.CreateModel(
            name='ClassInfo',
            fields=[
                ('classID', models.AutoField(primary_key=True, serialize=False)),
                ('className', models.CharField(max_length=30)),
            ],
        ),
    ]
